
<?php
if(isset($_POST['v_id'])){
	
		echo "<table id='safety' class='table table-striped table-bordered table-hover'>";
	   include("connection.php");
		 $sql="select * from car_safety_1 where v_id=".$_POST['v_id'];
		 $sql2="select * from car_safety_2 where v_id=".$_POST['v_id'];
		 $res=mysql_query($sql);
		 $res2=mysql_query($sql2);
		 $row=mysql_fetch_array($res);
		 $row2=mysql_fetch_array($res2);
		 $id=$row['v_id'];
		echo "<tr>";
			echo "<td colspan='2'><center><a href='carversion_safety_edit.php?vid=$id'><b><font size='4'>Edit</font></b></a><center></td>";
		echo "</tr>";
    echo "<tr>";
				echo "<td width='50%'>Anti-Lock Braking</td>";
				echo "<td>".$row['anti_lock_breaking']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Brake Assist</td>";			
				echo "<td>".$row['brake_assist']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Central Locking</td>";			
				echo "<td>".$row['central_locking']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Power Door Locks</td>";			
				echo "<td>".$row['power_door_locks']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Child Safety Locks</td>";			
				echo "<td>".$row['child_safety_locks']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Anti-Theft Alarm</td>";			
				echo "<td>".$row['anti_theft_alarm']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Driver Airbag</td>";			
				echo "<td>".$row['driver_airbag']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Passenger Airbag</td>";			
				echo "<td>".$row['passanger_airbag']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Side Airbag(Front)</td>";			
				echo "<td>".$row['side_airbag_front']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Side Airbag(Rear)</td>";			
				echo "<td>".$row['side_airbag_rear']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Night Rear View Mirror</td>";			
				echo "<td>".$row['night_rear_view_mirror']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Passenger Side Rear View Mirror</td>";			
				echo "<td>".$row['passenger_side_rear_mirror']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Xenon Headlamps</td>";			
				echo "<td>".$row['xenon_headlamps']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Rear Seat Belts</td>";			
				echo "<td>".$row['rear_seat_belts']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Seat Belt Warning</td>";			
				echo "<td>".$row['seat_bealt_warning']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Halogen Headlamps</td>";			
				echo "<td>".$row['halogen_headlamps']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Door Ajar Warning</td>";			
				echo "<td>".$row['door_ajar_warning']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Side Impact Beams</td>";			
				echo "<td>".$row2['side_impact_beams']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Front Impact Beams</td>";			
				echo "<td>".$row2['front_impact_beams']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Traction Control</td>";			
				echo "<td>".$row2['traction_control']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Adjustable Seats</td>";			
				echo "<td>".$row2['adjustable_seats']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Keyless Entry</td>";			
				echo "<td>".$row2['keyless_entry']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Tyre Pressure Monitor</td>";			
				echo "<td>".$row2['tyre_pressure_monitor']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Vehicle Stability Control System</td>";			
				echo "<td>".$row2['vehicle_stability_control']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Engine Immobilizer</td>";			
				echo "<td>".$row2['engine_immobilizer']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Crash Sensor</td>";			
				echo "<td>".$row2['crash_sensor']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Centrally Mounted Fuel Tank</td>";			
				echo "<td>".$row2['centrally_mounted_fueltank']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Engine Check Warning</td>";			
				echo "<td>".$row2['engine_check_warning']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Automatic Headlamps</td>";			
				echo "<td>".$row2['auto_headlamps']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Clutch Lock</td>";			
				echo "<td>".$row2['clutch_lock']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>EBD</td>";			
				echo "<td>".$row2['ebd']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Follow Me Home Headlamps</td>";			
				echo "<td>".$row2['follow_me_home_headlamp']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Rear Camera</td>";			
				echo "<td>".$row2['rear_camera']."</td>";
	echo "</tr>";
	echo "<tr>";
				echo "<td>Anti-Theft Device</td>";			
				echo "<td>".$row2['anti_theft_device']."</td>";
	echo "</tr>";


	

    echo "</table>";
	
}


?>
